name: Test Environment Caller

on:
  workflow_dispatch:
jobs:
  test-environment:
    strategy:
        matrix:
            env: ["dev", "prod", ""]
    name: Test with environement ${{ matrix.env }}
    uses: ./.github/workflows/reuseable_with_env.yaml
    with:
      environment: ${{ matrix.env }}
    secrets:
      required-secret: ${{ secrets.SECRET }}
  test-no-environment:
    name: Test with no environement
    uses: ./.github/workflows/reuseable_with_env.yaml
    secrets:
      required-secret: ${{ secrets.SECRET }}