name: Test Changed Files
on:
  pull_request:
    branches:
      - main
jobs:
  changed_files:
    permissions: {} # No permissions given
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: should_run/*
          files_ignore: should_run/but_not_me.txt
      - name: Skip step
        id: skip-step
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "sup"
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
  run_depdendent_test:
      needs: changed_files
      runs-on: ubuntu-latest
      if: needs.changed_files.outputs.any_changed == 'true'
      steps:
      - name: Run only if it path actually changed
        run: |
          echo "Second job ran"